/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as BestSellersRouteImport } from './routes/best-sellers'
import { Route as CommandeRouteImport } from './routes/commande'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as NouveautesRouteImport } from './routes/nouveautes'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as BoutiqueIndexRouteImport } from './routes/boutique.index'
import { Route as BoutiqueSlugRouteImport } from './routes/boutique.$slug'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CommandeConfirmationRouteImport } from './routes/commande_.confirmation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const BestSellersRoute = BestSellersRouteImport.update({
  id: '/best-sellers',
  path: '/best-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeRoute = CommandeRouteImport.update({
  id: '/commande',
  path: '/commande',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveautesRoute = NouveautesRouteImport.update({
  id: '/nouveautes',
  path: '/nouveautes',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueIndexRoute = BoutiqueIndexRouteImport.update({
  id: '/boutique/',
  path: '/boutique/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueSlugRoute = BoutiqueSlugRouteImport.update({
  id: '/boutique/$slug',
  path: '/boutique/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandeConfirmationRoute = CommandeConfirmationRouteImport.update({
  id: '/commande_/confirmation',
  path: '/commande/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/best-sellers': typeof BestSellersRoute
  '/commande': typeof CommandeRoute
  '/contact': typeof ContactRoute
  '/nouveautes': typeof NouveautesRoute
  '/panier': typeof PanierRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/boutique/': typeof BoutiqueIndexRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/best-sellers': typeof BestSellersRoute
  '/commande': typeof CommandeRoute
  '/contact': typeof ContactRoute
  '/nouveautes': typeof NouveautesRoute
  '/panier': typeof PanierRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/commande/confirmation': typeof CommandeConfirmationRoute
  '/boutique': typeof BoutiqueIndexRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/best-sellers': typeof BestSellersRoute
  '/commande': typeof CommandeRoute
  '/contact': typeof ContactRoute
  '/nouveautes': typeof NouveautesRoute
  '/panier': typeof PanierRoute
  '/boutique/$slug': typeof BoutiqueSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/commande_/confirmation': typeof CommandeConfirmationRoute
  '/boutique/': typeof BoutiqueIndexRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/best-sellers'
    | '/commande'
    | '/contact'
    | '/nouveautes'
    | '/panier'
    | '/boutique/$slug'
    | '/collections/$slug'
    | '/commande/confirmation'
    | '/boutique/'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/best-sellers'
    | '/commande'
    | '/contact'
    | '/nouveautes'
    | '/panier'
    | '/boutique/$slug'
    | '/collections/$slug'
    | '/commande/confirmation'
    | '/boutique'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/best-sellers'
    | '/commande'
    | '/contact'
    | '/nouveautes'
    | '/panier'
    | '/boutique/$slug'
    | '/collections/$slug'
    | '/commande_/confirmation'
    | '/boutique/'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BestSellersRoute: typeof BestSellersRoute
  CommandeRoute: typeof CommandeRoute
  ContactRoute: typeof ContactRoute
  NouveautesRoute: typeof NouveautesRoute
  PanierRoute: typeof PanierRoute
  BoutiqueSlugRoute: typeof BoutiqueSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  CommandeConfirmationRoute: typeof CommandeConfirmationRoute
  BoutiqueIndexRoute: typeof BoutiqueIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-sellers': {
      id: '/best-sellers'
      path: '/best-sellers'
      fullPath: '/best-sellers'
      preLoaderRoute: typeof BestSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande': {
      id: '/commande'
      path: '/commande'
      fullPath: '/commande'
      preLoaderRoute: typeof CommandeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveautes': {
      id: '/nouveautes'
      path: '/nouveautes'
      fullPath: '/nouveautes'
      preLoaderRoute: typeof NouveautesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/': {
      id: '/boutique/'
      path: '/boutique'
      fullPath: '/boutique/'
      preLoaderRoute: typeof BoutiqueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique/$slug': {
      id: '/boutique/$slug'
      path: '/boutique/$slug'
      fullPath: '/boutique/$slug'
      preLoaderRoute: typeof BoutiqueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commande_/confirmation': {
      id: '/commande_/confirmation'
      path: '/commande/confirmation'
      fullPath: '/commande/confirmation'
      preLoaderRoute: typeof CommandeConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BestSellersRoute: BestSellersRoute,
  CommandeRoute: CommandeRoute,
  ContactRoute: ContactRoute,
  NouveautesRoute: NouveautesRoute,
  PanierRoute: PanierRoute,
  BoutiqueSlugRoute: BoutiqueSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  CommandeConfirmationRoute: CommandeConfirmationRoute,
  BoutiqueIndexRoute: BoutiqueIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
